[Writable]
LogLevel = "DEBUG"

[Service]
Host = "edgex-device-mqtt"
Port = 49982
ConnectRetries = 3
Labels = []
OpenMsg = "device mqtt started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10
Type = "consul"

[Logging]
EnableRemote = false
File = "./device-mqtt.log"

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 50000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 50000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./custom-config"



# Pre-define Devices
[[DeviceList]]
  Name = "MQTTVideoAnalyticservice"
  Profile = "Device.MQTT.VideoAnalyticWrapper"
  Description = "MQTT device is created for sending VA analytics data to Edgex"
  Labels = [ "MQTT", "test"]
  [DeviceList.Protocols]
    [DeviceList.Protocols.mqtt]
       Schema = "tcp"
       Host = "mqtt"
       Port = "1883"
       ClientId = "CommandPublisher"
       User = "admin"
       Password = "public"
       Topic = "CommandTopic"
  [[DeviceList.AutoEvents]]
    Frequency = "20s"
    OnChange = false
    Resource = "testanalyticsdata"

# Driver configs
[Driver]
IncomingSchema = "tcp"
IncomingHost = "mqtt"
IncomingPort = "1883"
IncomingUser = "admin"
IncomingPassword = "public"
IncomingQos = "0"
IncomingKeepAlive = "3600"
IncomingClientId = "IncomingDataSubscriber"
IncomingTopic = "DataTopic"
ResponseSchema = "tcp"
ResponseHost = "mqtt"
ResponsePort = "1883"
ResponseUser = "admin"
ResponsePassword = "public"
ResponseQos = "0"
ResponseKeepAlive = "3600"
ResponseClientId = "CommandResponseSubscriber"
ResponseTopic = "ResponseTopic"